# Site settings
title: Vim China
email: vimchina
description: Happy Vimming!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vimchina.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  vimchina

# Build settings
markdown: kramdown

# Outputting
permalink:     /:year/:month/:day/:title.html
